apiVersion: v1
kind: Secret
metadata:
  name: cartest-secrets
  namespace: cartest
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root
  DB_USERNAME: app_admin
  DB_PASSWORD: app_admin_pass
  DINGGO_USERNAME: joesitu123@gmail.com
  DINGGO_KEY: joesitu123
